export const GET_ALL_TEAMS = 'GET_ALL_TEAMS';
export const ADD_TO_FAVORITE_TEAMS = 'ADD_TO_FAVORITE_TEAMS';
export const REMOVE_FROM_FAVORITE_TEAMS = 'REMOVE_FROM_FAVORITE_TEAMS';

export const GET_ALL_PLAYERS = 'GET_ALL_PLAYERS';
export const ADD_TO_FAVORITE_PLAYERS = 'ADD_TO_FAVORITE_PLAYERS';
export const REMOVE_FROM_FAVORITE_PLAYERS = 'REMOVE_FROM_FAVORITE_PLAYERS';
